/* COPYRIGHT (C) HARRY CLARK */

/* CS1_MCP Matrix Multiplication Calculator */

/* THIS FILE PERTAINS TO THE INITIALISATION OF THE MATRICES */
/* AND THE RESPECTIVE CALCUATION */

/* THE CALCULATOR WORKS ON THE BASIS OF THE USER PROVIDING */
/* THE DIMENSIONAL SIZES OF THE MATRICES AND THE PROGRAM */
/* CALCULATES THE CORRESPONDENCE */

/* NESTED INCLUDES */

#include "util.h"

#ifdef MATRIX_ARGS

static MATRIX* GET_MATRIX;

#endif